default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: diasdashboard
  username: postgres
  password: password

development:
  <<: *default
  database: diasdashboard_development

test:
  <<: *default
  database: diasdashboard_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>